package crb_web

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	"crb/models"
)

// NewCreateCopyParams creates a new CreateCopyParams object
// with the default values initialized.
func NewCreateCopyParams() CreateCopyParams {
	var ()
	return CreateCopyParams{}
}

// CreateCopyParams contains all the bound params for the create copy operation
// typically these are obtained from a http.Request
//
// swagger:parameters createCopy
type CreateCopyParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*copy data as octet stream
	  Required: true
	  In: body
	*/
	CopyData models.InputStream
	/*The id of the copy instance.
	  Required: true
	  In: path
	*/
	CopyID string
	/*copyInfo is user provided metadata
	  In: header
	*/
	CopyInfo *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *CreateCopyParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		o.CopyData = r.Body

	} else {
		res = append(res, errors.Required("copyData", "body"))
	}

	rCopyID, rhkCopyID, _ := route.Params.GetOK("copyId")
	if err := o.bindCopyID(rCopyID, rhkCopyID, route.Formats); err != nil {
		res = append(res, err)
	}

	if err := o.bindCopyInfo(r.Header[http.CanonicalHeaderKey("copyInfo")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateCopyParams) bindCopyID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.CopyID = raw

	return nil
}

func (o *CreateCopyParams) bindCopyInfo(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.CopyInfo = &raw

	return nil
}
